---

- name: Upload configuration
  copy:
    content: "{{ auditbeat_config }}"
    dest: /etc/auditbeat/auditbeat.yml
    owner: root
    group: root
    mode: 0o644
    validate: auditbeat test config --path.config %s
  notify: auditbeat restart service
