---

- include_vars: "{{ beats_flavor }}.yml"

- name: Merge user conf with defaults
  set_fact:
    beats_combined_config: >-
      {{
        _beats_default_config
        | combine(beats_config, recursive=True)
      }}
