---

- name: "{{ beats_flavor }}: Disable journald-audit on Linux"
  systemd:
    name: systemd-journald-audit.socket
    masked: true
    enabled: false
    state: stopped
  when:
    - beats_auditbeat_mask_journald_audit | bool
    - ansible_os_family != 'Windows'


- name: "{{ beats_flavor }}: Create rules directory"
  file:
    path: "{{ beats_auditbeat_rules_dir }}"
    state: directory

- name: "{{ beats_flavor }}: Upload rule files on Linux"
  template:
    src: "{{ item }}"
    dest: >-
      {{ beats_auditbeat_rules_dir }}/{{
        item | basename | regex_replace('^(.*)[.]j2', '\\1')
      }}
    owner: root
    group: root
    mode: 0o644
  loop: "{{ beats_auditbeat_rule_files }}"
  when: ansible_os_family != 'Windows'

- name: "{{ beats_flavor }}: Upload rules files on Windows"
  win_template:
    src: "{{ item }}"
    dest: >-
      {{ beats_auditbeat_rules_dir }}/{{
        item | basename | regex_replace('^(.*)[.]j2', '\\1')
      }}
  loop: "{{ beats_auditbeat_rule_files }}"
  when: ansible_os_family == 'Windows'
