---

- name: "{{ beats_flavor }}: auditbeat specific tasks on Linux"
  block:
    - name: "{{ beats_flavor }}: Disable journald-audit on Linux"
      systemd:
        name: systemd-journald-audit.socket
        masked: true
        enabled: false
        state: stopped
      when: beats_mask_journald_audit | bool

- name: "{{ beats_flavor }}: Upload rules bundled with the role on Linux"
      copy:
        src: "{{ item }}"
        dest: "/etc/beats/{{ beats_rules_dir }}/"
        owner: root
        group: root
        mode: 0o644
      loop: "{{ beats_enabled_bundled_rules }}"
  when: ansible_os_family != 'Windows'

- name: "{{ beats_flavor }}: Upload rules bundled with the role on Windows"
  win_copy:
    src: "{{ item }}"
    dest: "/etc/beats/{{ beats_rules_dir }}/"
  loop: "{{ beats_enabled_bundled_rules }}"
  when: ansible_os_family == 'Windows'
