---

- name: "{{ beats_flavor }}: Create inputs directory"
  block:
    - name: "{{ beats_flavor }}: Create inputs directory on Linux"
      file:
        path: "{{ beats_filebeat_inputs_dir }}"
        state: directory
      when: ansible_os_family != 'Windows'
    - name: "{{ beats_flavor }}: Create inputs directory on Windows"
      win_file:
        path: "{{ beats_filebeat_inputs_dir }}"
        state: directory
      when: ansible_os_family == 'Windows'

- name: "{{ beats_flavor }}: Upload inputs"
  block:
    - name: "{{ beats_flavor }}: Upload inputs on Linux"
      template:
        src: "{{ item }}"
        dest: >-
          {{ beats_filebeat_inputs_dir }}/{{
            item | basename | regex_replace('^(.*)[.]j2', '\\1')
          }}
      loop: "{{ beats_filebeat_input_files }}"
      when: ansible_os_family != 'Windows'
      notify: beats restart service

    - name: "{{ beats_flavor }}: Upload inputs on Windows"
      win_template:
        src: "{{ item }}"
        dest: >-
          {{ beats_filebeat_input_files }}/{{
            item | basename | regex_replace('^(.*)[.]j2', '\\1')
          }}
      loop: "{{ beats_filebeat_input_files }}"
      when: ansible_os_family == 'Windows'
      notify: beats restart service

- name: "{{ beats_flavor }}: Create modules directory"
  block:
    - name: "{{ beats_flavor }}: Create modules directory on Linux"
      file:
        path: "{{ beats_filebeat_modules_dir }}"
        state: directory
      when: ansible_os_family != 'Windows'
    - name: "{{ beats_flavor }}: Create modules directory on Windows"
      win_file:
        path: "{{ beats_filebeat_modules_dir }}"
        state: directory
      when: ansible_os_family == 'Windows'

- name: "{{ beats_flavor }}: Upload modules"
  block:
    - name: "{{ beats_flavor }}: Upload modules on Linux"
      template:
        src: "{{ item }}"
        dest: >-
          {{ beats_filebeat_modules_dir }}/{{
            item | basename | regex_replace('^(.*)[.]j2', '\\1')
          }}
      loop: "{{ beats_filebeat_module_files }}"
      when: ansible_os_family != 'Windows'
      notify: beats restart service

    - name: "{{ beats_flavor }}: Upload modules on Windows"
      win_template:
        src: "{{ item }}"
        dest: >-
          {{ beats_filebeat_modules_dir }}/{{
            item | basename | regex_replace('^(.*)[.]j2', '\\1')
          }}
      loop: "{{ beats_filebeat_module_files }}"
      when: ansible_os_family == 'Windows'
      notify: beats restart service

- name: "{{ beats_flavor }}: Enable filebeat modules"
  block:
    - name: "{{ beats_flavor }}: Enable filebeat modules on Linux"
      command: "{{ beats_linux_exec }} modules enable {{ beats_filebeat_modules | join(' ') }}"
      when: ansible_os_family != 'Windows'

    - name: "{{ beats_flavor }}: Enable filebeat modules on Windows"
      win_command: "{{ beats_win_exec }} modules enable {{ beats_filebeat_modules | join(' ') }}"
      when: ansible_os_family == 'Windows'
  when: beats_filebeat_modules | length > 0
