---

- name: Upload rules bundled with the role on Linux
  copy:
    src: "{{ item }}"
    dest: "/etc/beats/{{ beats_rules_dir }}/"
    owner: root
    group: root
    mode: 0o644
  loop: "{{ beats_heartbeat_monitor_files }}"
  when: ansible_os_family != 'Windows'

- name: Upload rules bundled with the role on Windows
  win_copy:
    src: "{{ item }}"
    dest: "/etc/beats/{{ beats_rules_dir }}/"
  loop: "{{ beats_heartbeat_monitor_files }}"
  when: ansible_os_family == 'Windows'
