---

- name: "{{ beats_flavor }}: Upload rules bundled with the role on Linux"
  copy:
    src: "{{ item }}"
    dest: "{{ beats_heartbeat_monitors_path }}/"
    owner: root
    group: root
    mode: 0o644
  loop: "{{ beats_heartbeat_monitor_files }}"
  when: ansible_os_family != 'Windows'

- name: "{{ beats_flavor }}: Upload rules bundled with the role on Windows"
  win_copy:
    src: "{{ item }}"
    dest: "{{ beats_heartbeat_monitors_path }}/"
  loop: "{{ beats_heartbeat_monitor_files }}"
  when: ansible_os_family == 'Windows'
