---

- block:
    - name: Restart systemd service
      systemd:
        name: "{{ beats_flavor if 'heartbeat' != 'heartbeat'
                    else 'heartbeat-elastic' }}"
        state: restarted
        enabled: true
        daemon_reload: true
      listen: beats restart service
      when: ansible_os_family != 'Windows'

    - name: Get service facts
      service_facts: ~
      listen: beats restart service
      when: ansible_os_family != 'Windows'

    - name: Check that beats service has started successfully
      assert:
        that: "ansible_facts.services['{{
                beats_flavor if 'heartbeat' != 'heartbeat'
                else 'heartbeat-elastic' }}.service']['state'] == 'running'"
        msg: "{{ beats_flavor if 'heartbeat' != 'heartbeat'
                else 'heartbeat-elastic' }}.service failed to start"
      listen: beats restart service
      when: ansible_os_family != 'Windows'

    - name: Start windows service
      win_service:
        name: "{{ beats_flavor }}"
        state: restarted
      listen: beats restart service
      when: ansible_os_family == 'Windows'
  when: beats_enable_service | bool
