---

- name: Restart systemd service
  systemd:
    name: "{{ beats_flavor }}"
    state: restarted
    daemon_reload: true
  listen: beats restart service

- name: Get service facts
  service_facts: ~
  listen: beats restart service

- name: Check that beats service has started successfully
  assert:
    that:
      "ansible_facts.services['{{ beats_flavor }}.service']['state'] == 'running'"
    msg: "{{ beats_flavor }}.service failed to start"
  listen: beats restart service
