---

- block:
    - name: "{{ beats_flavor }}: Restart systemd service"
      systemd:
        name: "{{ beats_flavor if beats_flavor != 'heartbeat'
                    else 'heartbeat-elastic' }}"
        state: restarted
        enabled: true
        daemon_reload: true
      listen: beats restart service
      when: ansible_os_family != 'Windows'

    - name: "{{ beats_flavor }}: Get service facts"
      service_facts: ~
      listen: beats restart service
      when: ansible_os_family != 'Windows'

    - name: "{{ beats_flavor }}: Check that beats service has started successfully"
      assert:
        that: "ansible_facts.services['{{
                beats_flavor if beats_flavor != 'heartbeat'
                else 'heartbeat-elastic' }}.service']['state'] == 'running'"
        msg: "{{ beats_flavor if beats_flavor != 'heartbeat'
                else 'heartbeat-elastic' }}.service failed to start"
      listen: beats restart service
      when: ansible_os_family != 'Windows'

    - name: "{{ beats_flavor }}: Start windows service"
      win_service:
        name: "{{ beats_flavor }}"
        state: restarted
      listen: beats restart service
      when: ansible_os_family == 'Windows'
  when: beats_enable_service | bool
