---

- name: Restart systemd service
  systemd:
    name: auditbeat
    state: restarted
    daemon_reload: true
  listen: auditbeat restart service

- name: Get service facts
  service_facts: ~
  listen: auditbeat restart service

- name: Check that auditbeat service has started successfully
  assert:
    that:
      'ansible_facts.services["auditbeat.service"]["state"] == "running"'
    msg: 'audibeat.service failed to start'
  listen: auditbeat restart service
