---

- name: "{{ beats_flavor }}: Override field settings"
  blockinfile:
    path: "{{ beats_combined_config.setup.template.fields
              | d(beats_path_config + '/fields.yml') }}"
    marker_begin: "{{ _beats__field_setting.marker_begin }}"
    marker_end: "{{ _beats__field_setting.marker_end }}"
    marker: "{mark}"
    block: "{{ _beats__field_setting.block }}"
    mode: 0o644
  loop: "{{ beats_setup_template_field_overrides }}"
  loop_control:
    loop_var: _beats__field_setting
