---

- name: Enable systemd service
  systemd:
    name: auditbeat
    state: started
    enabled: true

- name: Get service facts
  service_facts: ~

- name: Check that auditbeat service has started successfully
  assert:
    that:
      'ansible_facts.services["auditbeat.service"]["state"] == running'
    msg: 'audibeat.service failed to start'
