---

- name: Enable systemd service
  systemd:
    name: "{{ beats_flavor }}"
    state: started
    enabled: true

- name: Get service facts
  service_facts: ~

- name: Check that {{ beats_flavor }} service has started successfully
  assert:
    that:
      "ansible_facts.services['{{ beats_flavor }}.service']['state'] == 'running'"
    msg: "{{ beats_flavor }}.service failed to start"
