---

# TODO add test case to update keystore
# TODO enable full certificate verification
# TODO add test for custom beats_path_*
# TODO enable beats_check_output
# TODO configure a kibana endpoint
# TODO add winlogbeat tests

- name: Converge
  hosts: all
  roles:
    - ansible-role-beats
  vars_files:
    - converge-vars.yml
