---

dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  set -e
  pwd
  yamllint --config-file molecule/default/yamllint.yml .
  ansible-lint .
  flake8
platforms:
  - name: "instance-${MOLECULE_DISTRO:-ubuntu1604}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1604}-ansible:latest"
    command: ${MOLECULE_INIT_CMD-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pid: host
    capabilities:
      - AUDIT_CONTROL
      - AUDIT_READ
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    vvv: true
  env:
    IN_MOLECULE: 'true'
scenario:
  name: default
verifier:
  name: testinfra
  enabled: false
  lint:
    name: flake8
