---

# Default config coming with auditbeat 7.0
_beats_default_config:
  name: "{{ beats_name }}"
  path:
    home: "{{ beats_path_home }}"
    config: "{{ beats_path_config }}"
    data: "{{ beats_path_data }}"
    logs: "{{ beats_path_logs }}"
  auditbeat:
    modules:
      - module: auditd
        audit_rule_files:
          - "{{ beats_rules_dir }}/*.conf"
      - module: file_integrity
        paths:
          - /bin
          - /usr/bin
          - /sbin
          - /usr/sbin
          - /etc
      - module: system
        datasets:
          - host
          - login
          - package
          - user
        period: 1m
        user:
          detect_password_changes: true
        login.wtmp_file_pattern: /var/log/wtmp*
        login.btmp_file_pattern: /var/log/btmp*
      - module: system
        datasets:
          - process
          - socket
        period: 1s
  setup:
    template:
      settings:
        index:
          number_of_shards: 1
