---

_beats_default_config:
  name: "{{ beats_name }}"
  path:
    home: "{{ beats_path_home }}"
    config: "{{ beats_path_config }}"
    data: "{{ beats_path_data }}"
    logs: "{{ beats_path_logs }}"
  heartbeat:
    config:
      monitors:
        path: "{{ beats_heartbeat_monitors_path }}/*.yml"
      reload:
        enabled: true
        period: 5s
  setup:
    index:
      number_of_shards: 1
      codec: best_compression
