---

name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1

      - name: Install molecule
        run: pip3 install molecule[ansible,ansible-base,docker,lint]

      - name: Run a multi-line script
        run: molecule test
        env:
          IN_MOLECULE: true
