name: CI

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "5 5 1 * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - image: jrei/systemd-ubuntu:20.04
            instance: systemd-ubuntu-20.04
        beats_flavor:
          - auditbeat
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install molecule
        run: pip3 install ansible molecule molecule-docker

      - name: Run molecule test
        run: sudo $(which molecule) test
        env:
          MOLECULE_DISTRO: ${{ matrix.distro.image }}
          MOLECULE_INSTANCE_NAME: ${{ matrix.distro.instance }}
          MOLECULE_BEATS_FLAVOR: ${{ matrix.beats_flavor }}
