---

name: TODO issuer

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  issue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: "actions/checkout@master"
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v3.0.1-beta
        with:
          # Optional input that specifies whether to attempt to close an issue
          # when a TODO is removed.
          CLOSE_ISSUES: true
          # For multiline TODOs, format each line as a new paragraph when
          # creating the issue.
          AUTO_P: false
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
